In [2]:
import numpy as np

In [3]:
arr1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
strings = arr1[:5, :]
print(f'TASK 1: \n {strings} \n')

TASK 1: 
 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]] 



In [4]:
arr2 = arr1[:, 1:]
print('TASK 2: \n', f'Среднее значение: {np.mean(arr2, axis=0)} \n'
      f'Минимум: {arr2.min(axis=0)} \n',
      f'Максимум: {arr2.max(axis=0)} \n'
      f'Медиана: {np.median(arr2, axis=0)} \n')

TASK 2: 
 Среднее значение: [2.16010017e+04 9.05528000e+00] 
Минимум: [0 1] 
 Максимум: [2147483647         39] 
Медиана: [40.  9.] 



In [5]:
print(f'TASK 3: \n {np.clip(arr1[:, 1], 0, np.quantile(arr1[:, 1], 0.75))} \n')

TASK 3: 
 [60. 25. 10. ... 65.  5. 65.] 



In [6]:
print('TASK 4: \n', f'Продолжительность равна 0 у {np.count_nonzero(arr1[:, 1] == 0)} рецептов \n')

TASK 4: 
 Продолжительность равна 0 у 479 рецептов 



In [7]:
print(f'TASK 5: \n {len(np.unique(arr1[:, 0]))} \n')

TASK 5: 
 100000 



In [8]:
print('TASK 6: \n', f'{len(np.unique(arr1[:, 2]))}, \n {np.unique(arr1[:, 2])} \n')

TASK 6: 
 37, 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 



In [9]:
arr3 = np.copy(arr1)
smt = (arr3[:, 2] <= 5)
print(f'TASK 7: \n {arr3[smt, :]} \n')

TASK 7: 
 [[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 



In [10]:
number = arr1[:, 2] // arr1[:, 1]
print(f'TASK 8: \n {number.max(axis=0)} \n')

TASK 8: 
 23 



C:\Users\1\AppData\Local\Temp\ipykernel_15292\3017519935.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  number = arr1[:, 2] // arr1[:, 1]


In [11]:
arr4 = arr1[arr1[:, 1].argsort()][-100:]
print(f'TASK 9: \n {np.mean(arr4[:, 2])} \n')

TASK 9: 
 6.61 



In [12]:
number = 10
rand = np.random.randint(1, 100000, size=(1, 10))
print(f'TASK 10: \n {arr1[rand]} \n')

TASK 10: 
 [[[ 30477     10      6]
  [376262     90     15]
  [448580     28     10]
  [106428      5      5]
  [189801     90      9]
  [ 98522     20      9]
  [118105     75     10]
  [ 93161     15      5]
  [102491     35      6]
  [104726     25      6]]] 



In [13]:
less = (arr1[:, 2] <= np.mean(arr1[:, 2]))
print(f'TASK 11: \n {len(arr1[less, :]) / len(arr1) * 100} \n')

TASK 11: 
 58.802 



In [14]:
arr5 = arr1.copy()
rec = [1 if (row[1] <= 20) & (row[2] <= 5) else 0 for row in arr5]
arr6 = np.insert(arr5, 3, rec, axis=1)
print(f'TASK 12: \n {arr6} \n')

TASK 12: 
 [[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]] 



In [15]:
proc = (arr6[:, 3] == 1)
print('TASK 13: \n'
      f'{len(arr1[proc, :]) / len(arr6) * 100} \n')

TASK 13: 
9.552 

